name: Build and deploy ASP.NET Core app to Azure Web App - StudioWorld

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build webapp/webapp.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish webapp/webapp.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'studioworld'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          
      - name: Configure Azure App Service for .NET 8
        run: |
          echo "Setting up Azure App Service for .NET 8"
          echo "The application is targeting .NET 8, which is well-supported on Azure App Service"
          
      - name: Show deployed website URL
        run: |
          echo "Deployed to https://studioworld-ehgmexfxgkascvb2.eastus2-01.azurewebsites.net"
          echo "If you're still having issues, check the logs in the Azure Portal"
